### Get all pokemon
GET http://localhost:8080/v1/pokemons
Accept: application/json

### Get pokemon by id
GET http://localhost:8080/v1/pokemons/1
Accept: application/json

### Create pokemon
POST http://localhost:8080/v1/pokemons
Content-Type: application/json

{
  "name": "Charizard",
  "type": "Fire",
  "level": 36
}

### Update pokemon
PUT http://localhost:8080/v1/pokemons/5
Content-Type: application/json

{
  "name": "Charizard",
  "type": "Fire",
  "level": 20
}

### Delete pokemon
DELETE http://localhost:8080/v1/pokemons/5
Accept: application/json
